// source: cart.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.CartResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.CartProduct');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CartResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.CartResponse.repeatedFields_, null);
};
goog.inherits(proto.CartResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CartResponse.displayName = 'proto.CartResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.CartResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CartResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.CartResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CartResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CartResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    cartCountProduct: jspb.Message.getFieldWithDefault(msg, 1, 0),
    cartProductsList: jspb.Message.toObjectList(msg.getCartProductsList(),
    proto.CartProduct.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CartResponse}
 */
proto.CartResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CartResponse;
  return proto.CartResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CartResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CartResponse}
 */
proto.CartResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCartCountProduct(value);
      break;
    case 2:
      var value = new proto.CartProduct;
      reader.readMessage(value,proto.CartProduct.deserializeBinaryFromReader);
      msg.addCartProducts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CartResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CartResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CartResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CartResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCartCountProduct();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getCartProductsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.CartProduct.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 cart_count_product = 1;
 * @return {number}
 */
proto.CartResponse.prototype.getCartCountProduct = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.CartResponse} returns this
 */
proto.CartResponse.prototype.setCartCountProduct = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated CartProduct cart_products = 2;
 * @return {!Array<!proto.CartProduct>}
 */
proto.CartResponse.prototype.getCartProductsList = function() {
  return /** @type{!Array<!proto.CartProduct>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.CartProduct, 2));
};


/**
 * @param {!Array<!proto.CartProduct>} value
 * @return {!proto.CartResponse} returns this
*/
proto.CartResponse.prototype.setCartProductsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.CartProduct=} opt_value
 * @param {number=} opt_index
 * @return {!proto.CartProduct}
 */
proto.CartResponse.prototype.addCartProducts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.CartProduct, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.CartResponse} returns this
 */
proto.CartResponse.prototype.clearCartProductsList = function() {
  return this.setCartProductsList([]);
};


